proc_mgr: introducing the subscription API
microbuilder/linaro_step pull request #13
Opened 2022-06-15 22:21 UTC by uLipe

to receive data from nodes that completed their
processing chain.

Signed-off-by: Felipe Neves <felipe.neves@linaro.org>

2022-06-15 22:21 UTC, uLipe commented
@microbuilder PTAL

2022-06-15 22:35 UTC, uLipe commented
altough it has sample, I think this needs a proper unit tests before get merged.

2022-06-15 23:44 UTC, microbuilder commented
> altough it has sample, I think this needs a proper unit tests before get merged.

I was just going to say that. It really should have a test suite, but I'll do some testing of the sample, thanks!

2022-06-15 23:58 UTC, microbuilder requested changes

2022-06-15 23:58 UTC, microbuilder commented on Kconfig.step
> +	  Sets the maximum number of callback that the processor manager
```suggestion
	  Sets the maximum number of callbacks that the processor manager
```

2022-06-15 23:58 UTC, microbuilder commented on include/step/proc_mgr.h
> + * @brief Calllback deferred when a node chain is completed.
```suggestion
 * @brief Callback fired when a node chain is completed.
```

2022-06-15 23:58 UTC, microbuilder commented on samples/simple_subscription/README.rst
> +republishes the data to the chain.
```suggestion
This sample demonstrates how to use the subscription API.
A STeP node chain is created, and the external application
subscribes to the node chain's completion event, republishing
the data to the node chain.
```

2022-06-15 23:58 UTC, microbuilder commented on src/proc_mgr.c
> +	 * @brief Singly-linked list of subscribers callback.
```suggestion
	 * @brief Singly-linked list of subscriber callbacks.
```

2022-06-16 02:53 UTC, uLipe commented
Now we have tests for that. 

@microbuilder PTAL

2022-06-16 04:31 UTC, microbuilder approved these changes

2022-06-16 04:32 UTC, merged