samples: foc_controller: replace sine modulation
microbuilder/linaro_step pull request #16
Opened 2022-06-22 04:32 UTC by uLipe

with space vector pwm generation, also fixes the rotor
alignment procedure and a problem with step processor
manager that creates a dead loop thread when poll
rate is zero but event driven thread is not defined.

Signed-off-by: Felipe Neves <felipe.neves@linaro.org>

2022-06-22 04:32 UTC, uLipe commented
@microbuilder PTAL, this needs to be added befoere sensorless version gets in place.

2022-06-22 05:16 UTC, microbuilder requested changes

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.c
> +void foc_driver_set_duty_cicle(float dc_u, float dc_v, float dc_w)
```suggestion
void foc_driver_set_duty_cycle(float dc_u, float dc_v, float dc_w)
```

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.h
> +void foc_driver_set_duty_cicle(float dc_u, float dc_v, float dc_w);
```suggestion
void foc_driver_set_duty_cycle(float dc_u, float dc_v, float dc_w);
```

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.h
> + * @brief set inverter voltages based on duty cicle.
```suggestion
 * @brief set inverter voltages based on duty cycle.
```

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/foc_nodes.c
> +	foc_driver_set_duty_cicle(inverter_duties[0], inverter_duties[1], inverter_duties[2]);
```suggestion
	foc_driver_set_duty_cycle(inverter_duties[0], inverter_duties[1], inverter_duties[2]);
```

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/foc_svm.h
> + * @brief set inverter voltages based on duty cicle.
```suggestion
 * @brief set inverter voltages based on duty cycle.
```

2022-06-22 05:16 UTC, microbuilder commented on samples/foc_controller/src/main.c
> +	SHELL_CMD(align, NULL, "Align rotor and calibrate its position sensor", step_foc_cmd_align),
```suggestion
	SHELL_CMD(align, NULL, "Align rotor and calibrate it’s position sensor", step_foc_cmd_align),	
```

2022-06-22 10:42 UTC, uLipe commented
@microbuilder PTAL again.

2022-06-23 02:56 UTC, uLipe commented
@microbuilder PTAL

2022-06-23 04:07 UTC, microbuilder approved these changes

2022-06-23 04:08 UTC, merged