samples: added foc motor control  sample
microbuilder/linaro_step pull request #2
Opened 2022-05-18 02:44 UTC by uLipe

This PR add a sample of voltage mode FoC control for brushless motors.

2022-05-18 02:44 UTC, uLipe commented
@microbuilder PTAL

2022-05-18 20:50 UTC, microbuilder requested changes
Looks great, appreciate the excellent and very readable sample code. Some minor nits, but happy to merge this in once they're cleaned up.

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.c
> +#define PWM_PERIOD_NSEC 62500
If this is specific to the clock config on the PWM peripheral of the target MCU, we should find a way to calculate this without magic numbers or make it a KConfig value.

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.c
> +    uint16_t zero_offset;
Minor nit, but inconsistent leading whitespace:

```suggestion
	uint16_t raw;
	uint16_t zero_offset;
```

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.c
> +
nit: extra whitespace

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/src/foc_driver.c
> +	return 0;
Inconsistent leading whitespace

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/README.rst
> +Nucleo board.
Typo: AS5048?

If the AS5048 isn't register compatible with the AS5600, I would only mention the AS5600 here since that's the only driver we've implemented in this sample. If it's register compatible, perhaps mention something like:

```
... a magnetic encoder board like the AS5600, or something register compatible
like the AS5048, based on an I2C interface.
```

2022-05-18 20:50 UTC, microbuilder commented on samples/foc_controller/.gitignore
> +build/
nit: Missing new line

2022-05-19 10:59 UTC, uLipe commented on samples/foc_controller/src/foc_driver.c
> +#define PWM_PERIOD_NSEC 62500
This is just a generic period, it is not dependent on the target platform, the selected value is just a typical frequency that BLDC motors respond in continuous conduction mode.

In this case, can I leave this way?

2022-05-19 11:03 UTC, microbuilder approved these changes

2022-05-19 11:03 UTC, merged