WIP: samples: added STeP sample with processing nodes
microbuilder/linaro_step pull request #30
Opened 2022-12-05 17:29 UTC by uLipe

2022-12-28 17:03 UTC, uLipe commented
I forgot to tag 🤦 

@microbuilder PTAL.

2022-12-29 20:46 UTC, microbuilder requested changes

2022-12-29 20:46 UTC, microbuilder commented on samples/mobile_robot_kinematic_server/remote/src/kinematic_node.c
> +}
nit: Whitespace

2022-12-29 20:46 UTC, microbuilder commented on samples/mobile_robot_kinematic_server/src/kinematic_node.c
> +}
nit: whitespace

2022-12-29 20:54 UTC, microbuilder commented
@uLipe What version of Zephyr is this being built against, and what QEMU version are you using? For some reason, when I build and run via:

```bash
$ west build  -p always -b mps2_an521  modules/lib/step/samples/mobile_robot_kinematic_server
$ west build -t run
```

I can't enter anyting in the Zephyr shell, which is a first for me.

```bash
$ qemu-system-arm --version
QEMU emulator version 7.0.0 (v7.0.0-dirty)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

$ git describe
zephyr-v3.2.0-2456-g7c9d7922116
```

2023-01-02 14:50 UTC, uLipe commented
Just update the README.

2023-01-02 14:51 UTC, uLipe commented
@microbuilder , depending on version of Zephyr it is necessary to send a request for the remote processor before wakeup, it is also happens on the rpmsg demo, and only for the QEMU targets, I moved the wakeup request position and it should work now regardless the zephyr version .

2023-09-19 13:50 UTC, merged